AWSTemplateFormatVersion: 2010-09-09
Description: >-
  kevindanis.com Static Website  

Resources:
  S3BucketForRoot:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: kevindanis.com 
      WebsiteConfiguration:
        RedirectAllRequestsTo: 
          HostName: !Ref websiteHostingBucket
          Protocol: https
      AccessControl: BucketOwnerFullControl

  websiteHostingBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: www.kevindanis.com
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      VersioningConfiguration:
        Status: Enabled
      AccessControl: BucketOwnerFullControl
      Tags:
        - Key: deployment
          Value: kevindanis_com

Outputs:
  outputWebsiteURL:
    Value: !GetAtt 
      - websiteHostingBucket
      - WebsiteURL
    Description: Static website URL