AWSTemplateFormatVersion: 2010-09-09
Description: >-
  kevindanis.com Static Website  

Resources:
  S3BucketForRoot:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain # keep S3 bucket when its stack is deleted
    Properties:
      BucketName: kevindanis.com # use the name of your domain, such as example.com
      WebsiteConfiguration:
        RedirectAllRequestsTo: # Configure the bucket to route traffic to the subdomain bucket
          HostName: !Ref websiteHostingBucket
          Protocol: https
      AccessControl: BucketOwnerFullControl

  websiteHostingBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: www.kevindanis.com
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      VersioningConfiguration:
        Status: Enabled
      AccessControl: BucketOwnerFullControl
      Tags:
        - Key: deployment
          Value: kevindanis_com

Outputs:
  outputWebsiteURL:
    Value: !GetAtt 
      - websiteHostingBucket
      - WebsiteURL
    Description: Static website URL